import { invoke } from "@tauri-apps/api/core";
import { getCurrentWebview } from "@tauri-apps/api/webview";
import "./style.css";

type ItemStatus = "pending"|"processing"|"auto"|"auto-reviewed"|"manual"|"failed"|"done";
type AnalysisResult = { status:"auto"|"auto-reviewed"|"manual"|"failed"; suggested_number:string|null; candidates:string[]; reason:string; passes:Array<{stage:string;model:string;raw_value:string|null;normalized:string|null;uncertain:boolean;valid:boolean;note:string}> };
type QueueItem = { path:string; status:ItemStatus; analysis?:AnalysisResult; finalNumber:string; error?:string; thumb?:string; stagedPath?:string };
type Settings = { profileId:string;baseUrl:string;firstModel:string;reviewModel:string;strictModel:string;temperature:number;maxTokens:number;timeoutSeconds:number;maxDimension:number;firstPrompt:string;reviewPrompt:string;strictPrompt:string;numberPattern:string;separator:string;numberPadding:number;uppercase:boolean;removeSpaces:boolean;filenameTemplate:string;sequenceStart:number;sequenceDigits:number;batchName:string;outputDirectory:string };

const DEFAULT_PROMPTS={
 first:`你负责读取生产图片中的缸号。只输出图片中明确可见的编号；只有确实看不清字符时才标记 uncertain=true。格式正确、字符清楚时不要因为轻微反光或字体样式而标记不确定。严格返回 JSON：{"cylinder_number":"字符串或null","uncertain":true或false,"uncertain_characters":[],"multiple_candidates":[],"evidence":"不超过20字"}。不要输出 Markdown。`,
 review:`独立复核图片中的缸号。逐字符读取，不参考其他答案。清楚可见且只有一个编号时 uncertain=false；无法分辨的字符用 ?。严格返回 JSON：{"cylinder_number":"字符串或null","uncertain":true或false,"uncertain_characters":[],"multiple_candidates":[],"evidence":"不超过20字"}。`,
 strict:`加强复核图片中的缸号，重点比较 0/O、1/I、5/S、6/8、B/8。不要凭编号规律猜测。严格返回 JSON：{"cylinder_number":"字符串或null","uncertain":true或false,"uncertain_characters":[],"multiple_candidates":[],"evidence":"不超过20字"}。`
};
const DEFAULT_SETTINGS:Settings={profileId:"default",baseUrl:"https://dashscope.aliyuncs.com/compatible-mode/v1",firstModel:"qwen3.7-plus",reviewModel:"qwen-vl-ocr",strictModel:"qwen3.7-plus",temperature:.05,maxTokens:800,timeoutSeconds:90,maxDimension:2048,firstPrompt:DEFAULT_PROMPTS.first,reviewPrompt:DEFAULT_PROMPTS.review,strictPrompt:DEFAULT_PROMPTS.strict,numberPattern:"^[A-Z0-9]+(?:-[A-Z0-9]+)*$",separator:"-",numberPadding:0,uppercase:true,removeSpaces:true,filenameTemplate:"{{缸号}}_{{序号}}",sequenceStart:1,sequenceDigits:3,batchName:"",outputDirectory:""};

const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const input=(id:string)=>$<HTMLInputElement>(id), button=(id:string)=>$<HTMLButtonElement>(id), textarea=(id:string)=>$<HTMLTextAreaElement>(id);
let queue:QueueItem[]=[]; let stopRequested=false; let toastTimer=0; let settings=loadSettings();

function loadSettings():Settings{try{return {...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem("cylinder-renamer.settings.v2")||"{}")}}catch{return {...DEFAULT_SETTINGS}}}
function persist(){settings=readSettings();localStorage.setItem("cylinder-renamer.settings.v2",JSON.stringify(settings))}
function applySettings(){for(const [id,key] of [["base-url","baseUrl"],["first-model","firstModel"],["review-model","reviewModel"],["strict-model","strictModel"],["number-pattern","numberPattern"],["separator","separator"],["filename-template","filenameTemplate"],["batch-name","batchName"],["output-path","outputDirectory"]] as const) input(id).value=String(settings[key]); for(const [id,key] of [["temperature","temperature"],["max-tokens","maxTokens"],["timeout","timeoutSeconds"],["max-dimension","maxDimension"],["number-padding","numberPadding"],["sequence-start","sequenceStart"],["sequence-digits","sequenceDigits"]] as const) input(id).value=String(settings[key]); input("uppercase").checked=settings.uppercase;input("remove-spaces").checked=settings.removeSpaces;textarea("first-prompt").value=settings.firstPrompt;textarea("review-prompt").value=settings.reviewPrompt;textarea("strict-prompt").value=settings.strictPrompt}
function readSettings():Settings{return {...settings,baseUrl:input("base-url").value.trim(),firstModel:input("first-model").value.trim(),reviewModel:input("review-model").value.trim(),strictModel:input("strict-model").value.trim(),temperature:Number(input("temperature").value)||.05,maxTokens:Number(input("max-tokens").value)||800,timeoutSeconds:Number(input("timeout").value)||90,maxDimension:Number(input("max-dimension").value)||2048,firstPrompt:textarea("first-prompt").value.trim()||DEFAULT_PROMPTS.first,reviewPrompt:textarea("review-prompt").value.trim()||DEFAULT_PROMPTS.review,strictPrompt:textarea("strict-prompt").value.trim()||DEFAULT_PROMPTS.strict,numberPattern:input("number-pattern").value.trim(),separator:input("separator").value||"-",numberPadding:Number(input("number-padding").value)||0,uppercase:input("uppercase").checked,removeSpaces:input("remove-spaces").checked,filenameTemplate:input("filename-template").value.trim()||"{{缸号}}_{{序号}}",sequenceStart:Number(input("sequence-start").value)||1,sequenceDigits:Number(input("sequence-digits").value)||3,batchName:input("batch-name").value.trim(),outputDirectory:input("output-path").value.trim()}}
function aiConfig(){return{profile_id:settings.profileId,base_url:settings.baseUrl,first_model:settings.firstModel,review_model:settings.reviewModel,strict_model:settings.strictModel,temperature:settings.temperature,max_tokens:settings.maxTokens,timeout_seconds:settings.timeoutSeconds,max_dimension:settings.maxDimension,first_prompt:settings.firstPrompt,review_prompt:settings.reviewPrompt,strict_prompt:settings.strictPrompt}}
function rules(){return{pattern:settings.numberPattern,separator:settings.separator,number_padding:settings.numberPadding,uppercase:settings.uppercase,remove_spaces:settings.removeSpaces}}
function toast(message:string,error=false){clearTimeout(toastTimer);const n=$("toast");n.textContent=shortMessage(message);n.className=`toast visible${error?" error":""}`;toastTimer=window.setTimeout(()=>n.className="toast",3600)}
function shortMessage(value:string){const clean=value.replace(/^.*?：/,"").replace(/\s+/g," ").trim();return clean.length>52?`${clean.slice(0,52)}…`:clean}
function nameOf(path:string){return path.split(/[\\/]/).pop()||path}
function parentOf(path:string){const i=Math.max(path.lastIndexOf("\\"),path.lastIndexOf("/"));return i>0?path.slice(0,i):""}
function joinPath(...parts:string[]){const sep=parts[0]?.includes("\\")?"\\":"/";return parts.filter(Boolean).map((p,i)=>i===0?p.replace(/[\\/]+$/g,""):p.replace(/^[\\/]+|[\\/]+$/g,"")).join(sep)}
function outputRoot(){return settings.outputDirectory||joinPath(parentOf(queue[0]?.path||""),"缸号整理结果")}
function extParts(path:string){const n=nameOf(path),i=n.lastIndexOf(".");return i>0?{base:n.slice(0,i),ext:n.slice(i)}:{base:n,ext:""}}
function sanitize(n:string){return n.replace(/[<>:"/\\|?*\x00-\x1f]/g,"-").replace(/[. ]+$/g,"").slice(0,180)||"未命名"}
function targetName(item:QueueItem,index:number){if(!item.finalNumber)return nameOf(item.path);const p=extParts(item.path),d=new Date(),date=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}`,seq=String(settings.sequenceStart+index).padStart(settings.sequenceDigits,"0");let n=settings.filenameTemplate.replaceAll("{{缸号}}",item.finalNumber).replaceAll("{{序号}}",seq).replaceAll("{{日期}}",date).replaceAll("{{原文件名}}",p.base).replaceAll("{{批次}}",settings.batchName).replaceAll("{{扩展名}}",p.ext);n=sanitize(n);return settings.filenameTemplate.includes("{{扩展名}}")?n:n+p.ext}
function setView(view:"drop"|"progress"|"result"){$("drop-zone").classList.toggle("hidden",view!=="drop");$("progress-view").classList.toggle("hidden",view!=="progress");$("result-view").classList.toggle("hidden",view!=="result")}
async function refreshKey(){try{const ok=await invoke<boolean>("has_api_key",{profileId:"default"});$("key-status").textContent=ok?"已就绪":"尚未配置";$("key-badge").textContent=ok?"已保存":"未配置";$("key-badge").className=`state-badge${ok?" ready":""}`}catch{}}
function updateProgress(done:number,total:number,message:string){$("progress-count").textContent=`${done} / ${total}`;$("progress-title").textContent=`${total} 张图片`;$("progress-bar").style.width=`${total?done/total*100:0}%`;$("progress-message").textContent=message}
async function addPaths(paths:string[]){const imagePaths=paths.filter(p=>/\.(jpe?g|png|webp|bmp|gif)$/i.test(p));if(!imagePaths.length)return toast("没有找到支持的图片",true);const exists=new Set(queue.map(i=>i.path));for(const path of imagePaths)if(!exists.has(path))queue.push({path,status:"pending",finalNumber:""});await runQueue()}
async function runQueue(){persist();setView("progress");stopRequested=false;let done=queue.filter(i=>i.status!=="pending").length;updateProgress(done,queue.length,"正在识别缸号…");for(let i=0;i<queue.length;i++){if(stopRequested)break;const item=queue[i];if(!item||item.status!=="pending")continue;item.status="processing";updateProgress(done,queue.length,`正在处理 ${nameOf(item.path)}`);try{const a=await invoke<AnalysisResult>("analyze_image",{path:item.path,config:aiConfig(),rules:rules()});item.analysis=a;item.status=a.status;item.finalNumber=a.suggested_number||a.candidates[0]||""}catch(e){item.status="failed";item.error=String(e);item.finalNumber=""}done++;updateProgress(done,queue.length,`已完成 ${done} 张`)}await stageResults();renderResults();setView("result");toast(stopRequested?"已暂停，已完成部分已整理":"图片已整理完成")}
async function executeTo(folder:string,items:QueueItem[],named:boolean){if(!items.length)return;const root=joinPath(outputRoot(),folder);const payload=items.map(i=>({source_path:i.path,target_name:named?targetName(i,queue.indexOf(i)):nameOf(i.path)}));await invoke("execute_plan",{request:{output_dir:root,operation_mode:"copy",items:payload}});for(const i of items)i.stagedPath=joinPath(root,named?targetName(i,queue.indexOf(i)):nameOf(i.path))}
async function stageResults(){try{await executeTo("已完成",queue.filter(i=>i.status==="auto"||i.status==="auto-reviewed"),true);await executeTo("待确认",queue.filter(i=>i.status==="manual"),false);await executeTo("无法识别",queue.filter(i=>i.status==="failed"),false)}catch(e){toast(`整理文件失败：${String(e)}`,true)}}
function friendlyReason(item:QueueItem){if(item.status==="manual")return item.analysis?.candidates.length?"识别结果存在疑点，请确认编号":"编号无法确认";if(item.status==="failed")return "图片中没有读到有效编号";return ""}
async function ensureThumb(item:QueueItem,img:HTMLImageElement){if(item.thumb){img.src=item.thumb;return}try{item.thumb=await invoke<string>("load_thumbnail",{path:item.path,maxSide:360});img.src=item.thumb}catch{}}
function renderResults(){const auto=queue.filter(i=>["auto","auto-reviewed","done"].includes(i.status)).length,manual=queue.filter(i=>i.status==="manual").length,failed=queue.filter(i=>i.status==="failed").length;$("stat-auto").textContent=String(auto);$("stat-manual").textContent=String(manual);$("stat-failed").textContent=String(failed);$("result-title").textContent=`已整理 ${queue.length} 张图片`;const list=$("review-list");list.innerHTML="";queue.forEach((item,index)=>{if(item.status!=="manual"&&item.status!=="failed")return;const card=document.createElement("article");card.className="review-card";card.innerHTML=`<img class="review-thumb" alt="${nameOf(item.path)}"><div class="review-copy"><div class="review-title">${nameOf(item.path)}</div><div class="review-reason" title="${item.analysis?.reason||item.error||""}">${friendlyReason(item)}</div></div><input class="review-input" data-index="${index}" value="${item.finalNumber}" placeholder="填写缸号">`;list.append(card);void ensureThumb(item,card.querySelector("img")!)});if(!manual&&!failed)list.innerHTML='<div class="review-card"><div class="review-copy"><div class="review-title">没有需要处理的图片</div><div class="review-reason">所有图片都已自动命名</div></div></div>'}

button("select-images").onclick=async()=>addPaths(await invoke<string[]>("pick_images"));
button("new-task").onclick=()=>setView("drop");button("stop").onclick=()=>{stopRequested=true;button("stop").disabled=true};
button("open-settings").onclick=()=>{$("settings-drawer").classList.add("open");$("settings-drawer").setAttribute("aria-hidden","false")};document.querySelectorAll("[data-close-settings]").forEach(n=>n.addEventListener("click",()=>{$("settings-drawer").classList.remove("open");$("settings-drawer").setAttribute("aria-hidden","true");persist()}));
button("select-output").onclick=async()=>{const p=await invoke<string|null>("pick_directory");if(p){input("output-path").value=p;persist()}};
button("save-key").onclick=async()=>{const key=input("api-key").value.trim();if(!key)return toast("请填写 API Key",true);try{await invoke("save_api_key",{profileId:"default",apiKey:key});input("api-key").value="";await refreshKey();toast("API Key 已安全保存")}catch(e){toast(String(e),true)}};
button("clear-key").onclick=async()=>{await invoke("clear_api_key",{profileId:"default"});await refreshKey();toast("API Key 已清除")};button("test-api").onclick=async()=>{persist();try{toast(await invoke<string>("test_connection",{config:aiConfig()}))}catch(e){toast(String(e),true)}};
button("restore-prompts").onclick=()=>{textarea("first-prompt").value=DEFAULT_PROMPTS.first;textarea("review-prompt").value=DEFAULT_PROMPTS.review;textarea("strict-prompt").value=DEFAULT_PROMPTS.strict;persist();toast("默认提示词已恢复")};
$("review-list").addEventListener("input",e=>{const t=e.target as HTMLInputElement;if(!t.matches(".review-input"))return;const item=queue[Number(t.dataset.index)];if(item)item.finalNumber=t.value.trim()});
$("review-list").addEventListener("change",async e=>{const t=e.target as HTMLInputElement;if(!t.matches(".review-input"))return;const item=queue[Number(t.dataset.index)];if(!item||!item.finalNumber)return;try{await executeTo("已完成",[item],true);item.status="done";renderResults();toast("已完成命名")}catch(err){toast(String(err),true)}});
$("review-list").addEventListener("click",e=>{const img=(e.target as HTMLElement).closest<HTMLImageElement>(".review-thumb");if(!img)return;const card=img.closest(".review-card"),index=Number(card?.querySelector<HTMLInputElement>(".review-input")?.dataset.index);const item=queue[index];if(!item)return;$("preview-image").setAttribute("src",item.thumb||"");$("preview-dialog").showModal()});button("close-preview").onclick=()=>$("preview-dialog").close();
button("undo").onclick=async()=>{try{const s=await invoke<{completed:number}>("undo_last");toast(`已撤销 ${s.completed} 个文件`)}catch(e){toast(String(e),true)}};button("open-output").onclick=()=>toast(`结果保存在：${outputRoot()}`);
for(const n of document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>(".settings-drawer input,.settings-drawer textarea"))if(n.id!=="api-key")n.addEventListener("change",persist);
const dropZone=$("drop-zone");void getCurrentWebview().onDragDropEvent(event=>{if(event.payload.type==="over")dropZone.classList.add("dragging");if(event.payload.type==="leave")dropZone.classList.remove("dragging");if(event.payload.type==="drop"){dropZone.classList.remove("dragging");void addPaths(event.payload.paths)}});
applySettings();setView("drop");void refreshKey();
